name: TurboTrack
options:
  bundleIdPrefix: com.turbulenceforecastapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.6.0
settings:
  MARKETING_VERSION: "1.3.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: HQ59Y7A4T2
  CODE_SIGN_STYLE: Automatic
targets:
  TurboTrack:
    type: application
    platform: iOS
    sources:
      - TurboTrack
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAnalytics
      - package: firebase-ios-sdk
        product: FirebaseRemoteConfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.turbulenceforecastapp
        PRODUCT_NAME: "Turbulence Forecast"
        INFOPLIST_KEY_CFBundleDisplayName: "Turbulence Forecast"
        INFOPLIST_KEY_CFBundleName: "Turbulence Forecast"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Turbulence Forecast uses your location to show nearby turbulence reports."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
schemes:
  TurboTrack:
    build:
      targets:
        TurboTrack: all
